---
- name: Converge
  hosts: all
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: Copy something to test use of synchronize module
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /tmp/hosts-from-controller
    - name: "Include {{ cookiecutter.role_name }}"
      ansible.builtin.include_role:
        name: "{{ cookiecutter.role_name }}"
