---
ci:
  skip:
  # https://github.com/pre-commit-ci/issues/issues/55
  - ansible-lint
exclude: |
    (?x)(
        ^docs/conf.py$
    )
default_language_version:
  # make linting predictable, especially as we know that current pylint is not
  # working well with py311.
  python: python3.8
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - pydocstyle>=5.1.1
          - flake8-absolute-import
          - flake8-black>=0.1.1
          - flake8-docstrings>=1.5.0
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        args: []
        entry: mypy src/
        pass_filenames: false
        additional_dependencies:
          - ansible-compat>=2.2.0
          - molecule>=4.0.0
          - packaging
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
      - id: pylint
        additional_dependencies:
          # - astroid<=v2.11.6  #
          - ansible-core>=2.13
          - molecule>=4.0.0
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.7.0
    hooks:
      - id: ansible-lint
