---
ci:
  skip:
  # https://github.com/pre-commit-ci/issues/issues/55
  - ansible-lint
exclude: |
    (?x)(
        ^docs/conf.py$
    )
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pydocstyle>=5.1.1
          - flake8-absolute-import
          - flake8-black>=0.1.1
          - flake8-docstrings>=1.5.0
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        args: []
        entry: mypy src/
        pass_filenames: false
        additional_dependencies:
          - ansible-compat>=0.5.0
          - molecule>=4.0
          - packaging
          - types-PyYAML
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.9
    hooks:
      - id: pylint
        additional_dependencies:
          - ansible-core>=2.14.1
          - molecule>=4.0
          - pytest
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.10.2
    hooks:
      - id: ansible-lint
