---
exclude: |
    (?x)(
        ^docs/conf.py$
    )
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/python/black.git
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - pydocstyle>=5.1.1
          - flake8-absolute-import
          - flake8-black>=0.1.1
          - flake8-docstrings>=1.5.0
        language_version: python3
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        args: []
        entry: mypy lib/
        pass_filenames: false
        additional_dependencies:
          - ansible-lint>=5.1.0a0
          - molecule
          - packaging
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a3
    hooks:
      - id: pylint
        additional_dependencies:
          - ansible-core>=2.11.1
          - ansible-lint>=5.1.0a0
          - molecule
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.1.0a0
    hooks:
      - id: ansible-lint
