[build-system]
requires = [
  "pip >= 19.3.1",
  "setuptools >= 42",
  "setuptools_scm[toml] >= 6.1.1",
  "setuptools_scm_git_archive >= 1.1",
  "wheel >= 0.33.6",
]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = false

[tool.isort]
profile = "black"
float_to_top = true
known_third_party = [
  "molecule"
]

[tool.setuptools_scm]
local_scheme = "no-local-version"
